### ISSUE TITLE
Review Documentation Chapter

### ISSUE THREAD

**Issue by foster999** [best-practice-and-impact/qa-of-code-guidance#10]
Merged branch #4 , for migration to `jupyter-book`. But needs review at some point. Might also need more content?

**Comment by alexander-newton** [comment]
It will be reviewed.

**Comment by alexander-newton** [comment]
I've made some changes including splitting the chapter out @foster999 . I thought the content was good overall but this is a chapter that links closely with almost all others; so let's remember to review as we write more.

**Comment by foster999** [comment]
Thanks @alexander-newton 

Sorry, I should have mentioned that I've been moving the existing content into jupyter-book format. It's Markdown based, so I'll move the changes across before I merge those

Need to decide whether to split them into smaller subsections or keep as longer pages. See Core Prog vs Documentation [here](https://best-practice-and-impact.github.io/jupyter-books-test/index.html)
What do you reckon?

**Comment by alexander-newton** [comment]
Longer pages definitely :) but would prefer all the contents being in one place rather than split left and right.

**Comment by foster999** [comment]
Sounds good. The left contents are for separate chapters/pages, while the contents on the right side is the current pages headings. Can disable that, but it might be handy if we have long pages?

Agreed that I'd prefer it all on the left though - would be nice if it concertina'd the current section like the right side contents
