### ISSUE TITLE
Mention that CI/CD can be defined in code for reproducibility in different runners

### ISSUE THREAD

**Issue by foster999** [best-practice-and-impact/qa-of-code-guidance#110]
For example [https://dagger.io/](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdagger.io%2F&data=05%7C01%7CDavid.Foster%40ons.gov.uk%7Cb0b18385e75447a5edce08daf105470e%7C078807bfce824688bce00d811684dc46%7C0%7C0%7C638087302334842270%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=W3tTroM8HT245WpVi2mYcgJJepnfKktlybfhiOUbQNE%3D&reserved=0)

**Comment by RuSnook** [comment]
Will add to new CI/CD page
