### ISSUE TITLE
Rewrite Code configuration files section in configuration.md

### ISSUE THREAD

**Issue by RuSnook** [best-practice-and-impact/qa-of-code-guidance#122]
De-emphasise this section as better practice is to use dedicated config files.

**Comment by RuSnook** [comment]
Having looked into this further, I think that the whole page needs a rewrite to adjust the tone. Currently it's reading as a tutorial so needs to be reframed as guidance.

**Comment by sarahcollyer** [comment]
Covered in #147, so will close this issue.
