### ISSUE TITLE
Add information on integration testing

### ISSUE THREAD

**Issue by rowanhemsi** [best-practice-and-impact/qa-of-code-guidance#141]
Testing page currently lacks detail on integration and end to end testing. Page should cover what the purpose of these tests is, when to write them and what to think about when writing them. Users have expressed an interest in seeing an example of good practice

**Comment by foster999** [comment]
Fixed by #87

**Comment by sarahcollyer** [comment]
**DoD**

- [ ] Research into integration testing good practice has been conducted and understood
- [ ] Guidance with examples (as appropriate) has been added to the testing section
