### ISSUE TITLE
Fix project structure example rendering on testing page

### ISSUE THREAD

**Issue by rowanhemsi** [best-practice-and-impact/qa-of-code-guidance#142]
Example test directory structure is rendering as a list, rather than a clear representation of project structure

**Comment by rowanhemsi** [comment]
@RuSnook has fixed this either on a different page or on WIP branch

**Comment by RuSnook** [comment]
Yep have fixed all these project structure type issues just waiting for all the reviews to be done so I can deploy the updates which fix this. :)
