### ISSUE TITLE
Dead link: "Suggest Edit" on home page goes to 404

### ISSUE THREAD

**Issue by addledrabbit** [best-practice-and-impact/qa-of-code-guidance#160]
Pressing the "Suggest Edit" button at the top-right of the home page, goes to Error 404.

(https://best-practice-and-impact.github.io/qa-of-code-guidance/intro.html)

**Comment by JT-39** [comment]
I have also come across this.

I think this is an issue across the book. It looks like its because the link is to the branch master/... but this has now been renamed main/...
