### ISSUE TITLE
Putting the duck in Duck Book

### ISSUE THREAD

**Issue by tony-stone** [best-practice-and-impact/qa-of-code-guidance#166]
There is no way you can make this public and not explain to a general readership _why_ it is known as the Duck Book.

In short: what the the duck is a Duck Book?

**Comment by RichardP-tt** [comment]
I've heard it's because it's water-based (AQUA book) and is a quacker (QUality Assurance of C(K)ode for Analysis and Research)?

**Comment by tony-stone** [comment]
And I thought initialisms and acronyms in academia were contrived… 😉

**Comment by rowanhemsi** [comment]
You're exactly right @RichardP-tt, the guidance sit on top of [The Aqua Book: guidance on producing quality analysis for government](https://www.gov.uk/government/publications/the-aqua-book-guidance-on-producing-quality-analysis-for-government) and I think what started as a bit of an inside joke became the most common name 😅

**Comment by tony-stone** [comment]
Great, thanks @rowanhemsi  for confirming @RichardP-tt ‘s input. A quacker indeed.

My audience appreciated the explanation of the name with a groan 😂
