### ISSUE TITLE
Add suggested definitions to glossary

### ISSUE THREAD

**Issue by sarahcollyer** [best-practice-and-impact/qa-of-code-guidance#173]
[Glossary V2.docx](https://github.com/best-practice-and-impact/qa-of-code-guidance/files/14833065/Glossary.V2.docx)

Migration & pop stats have collated together some definitions they would like to see added to the glossary. This exercise was led by Graham Greenless.

We should review their suggestions and add to the glossary as appropriate.

**Comment by giro090** [comment]
I suggest we also include 'interactive running' and 'procedural running' as these are technical terms that are used in the definitions. Also 'attribute' for helping explain methods/classes.
