### ISSUE TITLE
include mocking examples & discussion in testing code section

### ISSUE THREAD

**Issue by r-leyshon** [best-practice-and-impact/qa-of-code-guidance#196]

**Comment by giro090** [comment]
I've put out a call on our internal open source language user groups, as well as the x-government data science slack, for a reviewer with technical experience in this area to sense-check my work. If there are any volunteers, it would be great to hear from you!

**Comment by r-leyshon** [comment]
> I've put out a call on our internal open source language user groups, as well as the x-government data science slack, for a reviewer with technical experience in this area to sense-check my work. If there are any volunteers, it would be great to hear from you!

Happy to help @gisellerosetta - is there a PR? Is it python or R?

**Comment by giro090** [comment]
Hi @r-leyshon, thank you - the PR will be ready sometime this week, I'll tag you when it's open. It's python based.

**Comment by r-leyshon** [comment]
> Hi @r-leyshon, thank you - the PR will be ready sometime this week, I'll tag you when it's open. It's python based.

Sounds very useful. OK I'll keep an eye out for notifications.

**Comment by giro090** [comment]
Hi @r-leyshon, I've opened a PR [here ](https://github.com/best-practice-and-impact/qa-of-code-guidance/pull/205)- I can't add you as an official reviewer, but please by all means leave any comments. I'm particularly interested in technical feedback, but welcome any suggestions for improvement.
