### ISSUE TITLE
Add examples to reducing repetition in tests to demonstrate these

### ISSUE THREAD

**Issue by alexander-newton** [best-practice-and-impact/qa-of-code-guidance#29]

**Comment by mitches-got-glitches** [comment]
Hi Alex,  I have quite a few examples of parametrising tests using a number of different methods. Currently uploading them to an existing repo of mine but I'd be happy to collaborate to provide some examples for the book.

**Comment by foster999** [comment]
Hey @mitches-got-glitches, please feel free to create a PR to include your examples in the existing content. Don't worry if this requires rearranging or rewriting other parts of that section, as it's very much draft at the min.

If you don't get chance, please point to your repo and I'll borrow the examples when I have time to rework this section.

**Comment by shilohd** [comment]
@mitches-got-glitches do you still have these examples of parametrising tests? We are looking to expand our testing guidance. Related to issue #27

**Comment by sarahcollyer** [comment]
***DoD**

- [ ] Find existing examples of modular test code OR write an example demonstrating this
- [ ] Add code examples to testing section under "Write test code only once"
- [ ] Link to examples (if appropriate/necessary)
