### ISSUE TITLE
Version Control - removing files

### ISSUE THREAD

**Issue by Kiki-Jiji** [best-practice-and-impact/qa-of-code-guidance#56]
_In section- Handling data breaches via Git, in warning box._ 

BFG repo-cleaner tool I think is slightly old, the recommended seems to be [git-filter-repo ](https://github.com/newren/git-filter-repo) 

 > git filter-repo is now recommended by the [git project](https://git-scm.com/docs/git-filter-branch#_warning) instead of git filter-branch.

An added bonus, you can install using pip! I have tried and it does work on ONS machines.

```bash 
pip3 install git-filter-repo
git filter-repo --strip-blobs-bigger-than 2M
```
The above worked for me in removing some large files on an ONS laptop using the Anaconda PowerShell Prompt.

**Comment by foster999** [comment]
Cheers for this @Kiki-Jiji, shall get it updated!

![Shredder](https://thumbs.gfycat.com/CreativeEasyCony-size_restricted.gif)
