### ISSUE TITLE
GitHub button "suggest edit" returns 404

### ISSUE THREAD

**Issue by todd-d-desnz** [best-practice-and-impact/qa-of-code-guidance#68]
Every page has a GitHub button (for want of a better word) on the top right:
![image](https://user-images.githubusercontent.com/93770925/162934533-27424434-5bb6-423c-a57d-8b4ef512533e.png)

If you click "suggest edit", you get taken to a 404 page. The typical link is as follows:
https://github.com/best-practice-and-impact/qa-of-code-guidance/edit/master/intro.md

I believe the equivalent correct link should include /book/  - though for non-collaborators, it invites you to create a fork:
https://github.com/best-practice-and-impact/qa-of-code-guidance/edit/master/book/intro.md

**Comment by alexander-newton** [comment]
creating a fork is expected behaviour, but thanks for flagging the other issue.

**Comment by foster999** [comment]
This seems to be working fine now, so must have been fixed since the last comment
