### ISSUE TITLE
Minor typo on /intro.md "it's version number"

### ISSUE THREAD

**Issue by todd-d-desnz** [best-practice-and-impact/qa-of-code-guidance#69]
https://github.com/best-practice-and-impact/qa-of-code-guidance/blob/c07bfef4c90a0f42ec141744ebcb2b06526244aa/book/intro.md?plain=1#L7

"You can refer to the current version of the guidance by it's version number"
should be
"You can refer to the current version of the guidance by **its** version number"

**Comment by foster999** [comment]
Thanks, this will be revised an upcoming change 😄
