### ISSUE TITLE
Issue on page /core_programming.html

### ISSUE THREAD

**Issue by todd-d-desnz** [best-practice-and-impact/qa-of-code-guidance#70]
Under 'Software ideas for analysts'; under 'Don't repeat yourself', the second R snippet reads:

> get_odd <- function(numbers) {
>   odd_numbers = []
>   for (number in first_ten_numbers) {
>     if (number % 2 == 1) {
>       odd_first_ten_numbers.append(number)
>     }
>   }
>   return odd_numbers
> }

This should be:

> get_odd <- function(numbers) {
  odd_numbers = c()
  for (number in numbers) {
    if (number %% 2 == 1) {
      odd_numbers <- c(odd_numbers, number)
    }
  }
  return(odd_numbers)
}

As written, the code returns a number of errors, because:
- "= []" does not work in R - should be "c()"
- the function is passed "numbers" but tries to use "first_ten_numbers"
- Remainder division needs %% not %
- .append does not work in R
- the function changes odd_first_ten_numbers but tries to return odd_numbers
- the function return needs brackets around the object

**Comment by alexander-newton** [comment]
@shilohd we should also add continuous integration to check all these snippets
