### ISSUE TITLE
Version control chapter blocked by zscaler

### ISSUE THREAD

**Issue by ghost** [best-practice-and-impact/qa-of-code-guidance#71]
Not sure if this really counts as an issue, as I'm not sure it is solveable, but I thought you might like to know that DLUHC are blocking the chapter on version control. I asked them to unblock it and got this response:

> Hi @Matthew Roberts, regarding the issues you are experiencing accessing the ( https://best-practice-and-impact.github.io/qa-of-code-guidance/version_control.html) website. As a matter of routine any website that is blocked by our security system is then checked to see why the block occurred. Our website checker runs any website through a number of different testing systems provided by Globally recognised security partners. That testing has indicated that the ( https://best-practice-and-impact.github.io/qa-of-code-guidance/version_control.html website is categorised as "malicious" by at least one of those testing systems. This means that the site is using tools or techniques that are considered to be actively hostile to those browsing to it. For example it may try to load malware or inject harmful code, or link your browser to other sites that are also actively hostile to your browser or PC. For this reason the Department is not prepared to unblock this site. We would also not recommend using any other device to browse to this site. Therefore we cannot approved your request. Best Regards.

I asked what the tools and techniques were and was told:

> Hi @Matthew Roberts, we ran a Zscaler Risk Analyzer report which stated the site as Malicious, the URL is considered as "PHISHING" therefore we are unable to unblock the site. I hope that helps.

All the other chapters load fine.

**Comment by alexander-newton** [comment]
that's bizarre. Thanks for flagging. Can you send me an email on alexander.newton@ons.gov.uk and get me in touch with them? We've had similar issues before...
