### ISSUE TITLE
Point to the RAP pathway

### ISSUE THREAD

**Issue by foster999** [best-practice-and-impact/qa-of-code-guidance#90]
We need to point users to the RAP pathway for learning the relevant skills, before they use the book to refine their good practices.

**Comment by foster999** [comment]
#100 adds a link to the intro page, but this will need updating to the new platform URL in the new year

**Comment by foster999** [comment]
Pathway currently down - update link once it's live again

**Comment by RuSnook** [comment]
Link has been updated in the #100
