### ISSUE TITLE
Update tools page

### ISSUE THREAD

**Issue by foster999** [best-practice-and-impact/qa-of-code-guidance#96]
Add:

- [x] Quarto
- [x] a11ytables
- [x] hamilton (python)
- [x] chispa
- [x] splink
- [x] fusen

**Comment by RuSnook** [comment]
Copied these from duplicate ticket:

- [x] polars
- [x] renv
- [x] pre-commit
- [ ] assumptions

**Comment by RuSnook** [comment]
@foster999 is there a link for 'assumptions'? I'm not sure if this is a specific package.
